/**
 * Message IDs for the internal lifecycle surfaces: renewals, collections,
 * provisioning, migrations and reports, and the frame and review dialog they
 * share. The wording lives in `src/i18n/messages/operations-finance.ts` in
 * every interface language; this map only says which message each part of a
 * page shows, so a view reads `t(copy.title)`.
 */
export const lifecycleCopy = {
  frame: {
    eyebrow: "operations.finance.frame.eyebrow",
    provenance: "operations.finance.frame.provenance",
    projectionCurrent: "operations.finance.frame.current",
    projectionStale: "operations.finance.frame.stale",
    readAtLoad: "operations.finance.frame.current",
    readFailed: "operations.finance.frame.unreadable",
    readFailedDetail: "operations.finance.frame.unreadable.detail",
    notWired: "operations.finance.frame.unwired",
    notWiredDetail: "operations.finance.frame.unwired.detail",
    guidedTitle: "operations.finance.frame.guided",
    guidedDetail: "operations.finance.frame.guided.detail",
  },
  evidence: {
    technical: "operations.finance.evidence.technical",
    record: "operations.finance.evidence.record",
    entry: "operations.finance.evidence.entry",
    sourceRecord: "operations.finance.evidence.sourceRecord",
    orderId: "operations.finance.evidence.orderId",
    invoiceId: "operations.finance.evidence.invoiceId",
    billingAccount: "operations.finance.evidence.billingAccount",
    recordId: "operations.finance.evidence.recordId",
  },
  renewals: {
    title: "operations.finance.renewals.title",
    description: "operations.finance.renewals.description",
    summaryLabel: "operations.finance.renewals.summaryLabel",
    windowMeta: "operations.finance.renewals.windowMeta",
    caption: "operations.finance.renewals.caption",
    columns: {
      route: "operations.finance.column.route",
      notice: "operations.finance.renewals.column.notice",
      serviceTerm: "operations.finance.renewals.column.serviceTerm",
    },
    invoicedLabel: "operations.finance.renewals.column.invoiced",
    riskUnrecorded: "operations.finance.renewals.riskUnrecorded",
    routeUnrecorded: "operations.finance.renewals.routeUnrecorded",
    noNoticeDate: "operations.finance.renewals.window.unscheduled",
    termUnrecorded: "operations.finance.renewals.termUnrecorded",
    noInvoices: "operations.finance.renewals.noInvoices",
    invoiceCount: "operations.finance.renewals.invoiceCount",
    empty: "operations.finance.renewals.empty",
  },
  collections: {
    title: "operations.finance.collections.title",
    description: "operations.finance.collections.description",
    summaryLabel: "operations.finance.collections.summaryLabel",
    openTotal: "operations.finance.collections.openTotal",
    openCount: "operations.finance.collections.openCount",
    overdueTotal: "operations.finance.collections.overdueTotal",
    overdueCount: "operations.finance.collections.overdueCount",
    oldest: "operations.finance.collections.oldest",
    days: "operations.finance.collections.days",
    priorityBody: "operations.finance.collections.priorityBody",
    mixedCurrency: "operations.finance.collections.mixedCurrency",
    tableHeading: "operations.finance.collections.tableHeading",
    tableSubheading: "operations.finance.collections.tableSubheading",
    tableMeta: "operations.finance.collections.tableMeta",
    empty: "operations.finance.collections.empty",
    caption: "operations.finance.collections.caption",
    columns: {
      priority: "operations.finance.collections.column.priority",
      age: "operations.finance.collections.column.age",
    },
    priorityRank: "operations.finance.collections.priorityRank",
    paidOn: "operations.finance.collections.paidOn",
    noDueDate: "operations.finance.collections.noDueDate",
  },
  provisioning: {
    title: "operations.finance.provisioning.title",
    description: "operations.finance.provisioning.description",
    summaryLabel: "operations.finance.provisioning.summaryLabel",
    providerOperations: "operations.finance.provisioning.providerOperations",
    providerOperationsDetail:
      "operations.finance.provisioning.providerOperations.detail",
    terminations: "operations.finance.provisioning.terminations",
    terminationsDetail: "operations.finance.provisioning.terminations.detail",
    highRiskDetail: "operations.finance.provisioning.highRisk.detail",
    retryTitle: "operations.finance.provisioning.retryTitle",
    retryBody: "operations.finance.provisioning.retryBody",
    recoveryLink: "operations.finance.provisioning.recoveryLink",
    unclassified: "operations.finance.provisioning.unclassified",
    tableHeading: "operations.finance.provisioning.tableHeading",
    recordCount: "operations.finance.provisioning.recordCount",
    empty: "operations.finance.provisioning.empty",
    caption: "operations.finance.provisioning.caption",
    columns: {
      record: "operations.finance.provisioning.column.record",
      kind: "operations.finance.provisioning.column.kind",
      provider: "operations.finance.provisioning.column.provider",
      attempts: "operations.finance.provisioning.column.attempts",
    },
    kinds: {
      providerOperation:
        "operations.finance.provisioning.kind.providerOperation",
      termination: "operations.finance.provisioning.kind.termination",
      unclassified: "operations.finance.provisioning.kind.unclassified",
    },
    noAttempts: "operations.finance.provisioning.noAttempts",
    nextAttempt: "operations.finance.provisioning.nextAttempt",
    noRetry: "operations.finance.provisioning.noRetry",
    endsOn: "operations.finance.provisioning.endsOn",
  },
  handoff: {
    label: "operations.finance.handoff.label",
    heading: "operations.finance.handoff.heading",
    intro: "operations.finance.handoff.intro",
    serviceStarts: "operations.finance.handoff.serviceStarts",
    submitted: "operations.finance.handoff.submitted",
    submit: "operations.finance.handoff.submit",
    submitting: "operations.finance.handoff.submitting",
    historical: "operations.finance.handoff.historical",
    empty: "operations.finance.handoff.empty",
    received: "operations.finance.handoff.received",
    forbidden: "operations.finance.handoff.forbidden",
    refused: "operations.finance.handoff.refused",
    failed: "operations.finance.handoff.failed",
  },
  migrations: {
    title: "operations.finance.migrations.title",
    description: "operations.finance.migrations.description",
    unwired: "operations.finance.migrations.unwired",
    illustrativeTitle: "operations.finance.migrations.illustrativeTitle",
    illustrativeBody: "operations.finance.migrations.illustrativeBody",
    summaryLabel: "operations.finance.migrations.summaryLabel",
    cards: {
      toReview: "operations.finance.migrations.cards.toReview",
      toReviewDetail: "operations.finance.migrations.cards.toReview.detail",
      ambiguous: "operations.finance.migrations.cards.ambiguous",
      ambiguousDetail: "operations.finance.migrations.cards.ambiguous.detail",
      noMatch: "operations.finance.migrations.cards.noMatch",
      noMatchDetail: "operations.finance.migrations.cards.noMatch.detail",
    },
    ambiguityTitle: "operations.finance.migrations.ambiguityTitle",
    ambiguityBody: "operations.finance.migrations.ambiguityBody",
    candidatesLabel: "operations.finance.migrations.candidatesLabel",
    relationships: {
      directBuyer: "operations.finance.migrations.relationship.directBuyer",
      subsidiary: "operations.finance.migrations.relationship.subsidiary",
      distributor: "operations.finance.migrations.relationship.distributor",
    },
    badge: {
      decided: "operations.finance.migrations.badge.decided",
      possibleMatches: "operations.finance.migrations.badge.possibleMatches",
      single: "operations.finance.migrations.badge.single",
      none: "operations.finance.migrations.badge.none",
    },
    confidenceLabel: "operations.finance.migrations.confidenceLabel",
    noMatch: "operations.finance.migrations.noMatch",
    search: {
      label: "operations.finance.migrations.search.label",
      placeholder: "operations.finance.migrations.search.placeholder",
      placeholderEmpty: "operations.finance.migrations.search.placeholderEmpty",
      helpAmbiguous: "operations.finance.migrations.search.helpAmbiguous",
      helpSingle: "operations.finance.migrations.search.helpSingle",
      helpNone: "operations.finance.migrations.search.helpNone",
    },
    attestation: "operations.finance.migrations.attestation",
    evidenceSummary: "operations.finance.migrations.evidenceSummary",
    ids: {
      migration: "operations.finance.migrations.id.migration",
      sourceReference: "operations.finance.migrations.id.sourceReference",
      submittedAccount: "operations.finance.migrations.id.submittedAccount",
    },
    decision: {
      linked: "operations.finance.migrations.decision.linked",
      staged: "operations.finance.migrations.decision.staged",
    },
    reasons: {
      ambiguous: "operations.finance.migrations.reason.ambiguous",
      selectAccount: "operations.finance.migrations.reason.selectAccount",
      confirmEvidence: "operations.finance.migrations.reason.confirmEvidence",
      readyToLink: "operations.finance.migrations.reason.readyToLink",
      newAccountReview: "operations.finance.migrations.reason.newAccountReview",
    },
    review: {
      linkAction: "operations.finance.migrations.review.linkAction",
      createAction: "operations.finance.migrations.review.createAction",
      linkEntity: "operations.finance.migrations.review.linkEntity",
      linkImpact: "operations.finance.migrations.review.linkImpact",
      createImpact: "operations.finance.migrations.review.createImpact",
      policyBasis: "operations.finance.migrations.review.policyBasis",
      linkDownstream: "operations.finance.migrations.review.linkDownstream",
      createDownstream: "operations.finance.migrations.review.createDownstream",
      technicalId: "operations.finance.migrations.review.technicalId",
      technicalIdWithAccount:
        "operations.finance.migrations.review.technicalIdWithAccount",
      actorAuthority: "operations.finance.migrations.review.actorAuthority",
      linkTrigger: "operations.finance.migrations.review.linkTrigger",
      createTrigger: "operations.finance.migrations.review.createTrigger",
      confirm: "operations.finance.migrations.review.confirm",
      blocked: "operations.finance.migrations.review.blocked",
    },
  },
  reports: {
    title: "operations.finance.reports.title",
    description: "operations.finance.reports.description",
    filtersLabel: "operations.finance.reports.filtersLabel",
    reportLabel: "operations.finance.reports.column.report",
    allReports: "operations.finance.reports.allReports",
    reportHelp: "operations.finance.reports.reportHelp",
    exportsHeading: "operations.finance.reports.exportsHeading",
    exportsCaption: "operations.finance.reports.exportsCaption",
    exportCount: "operations.finance.reports.exportCount",
    exportsEmpty: "operations.finance.reports.exportsEmpty",
    exportsFilterEmpty: "operations.finance.reports.exportsFilterEmpty",
    columns: {
      report: "operations.finance.reports.column.report",
      document: "operations.finance.reports.column.document",
      recorded: "operations.finance.reports.column.recorded",
    },
    documentPending: "operations.finance.reports.documentPending",
    catalogueHeading: "operations.finance.reports.catalogueHeading",
    catalogueDescription: "operations.finance.reports.catalogueDescription",
    scopeLabel: "operations.finance.reports.scopeLabel",
    allAccounts: "operations.finance.reports.allAccounts",
    accountHelp: "operations.finance.reports.accountHelp",
    selectedAccountEvidence:
      "operations.finance.reports.selectedAccountEvidence",
    submittedAccount: "operations.finance.reports.submittedAccount",
    downloadedForAccount: "operations.finance.reports.downloadedForAccount",
    downloadedForScope: "operations.finance.reports.downloadedForScope",
    exportFailed: "operations.finance.reports.exportFailed",
    exporting: "operations.finance.reports.exporting",
    exportCsv: "operations.finance.reports.exportCsv",
    names: {
      revenue_forecast: "operations.finance.report.revenueForecast",
      capacity_planning: "operations.finance.report.capacityPlanning",
      renewal_churn_exposure: "operations.finance.report.renewalChurnExposure",
      partner_performance: "operations.finance.report.partnerPerformance",
      funnel_cycle_time: "operations.finance.report.funnelCycleTime",
      margin_poc_cost: "operations.finance.report.marginPocCost",
      arr_mrr: "operations.finance.report.arrMrr",
      billing_collections: "operations.finance.report.billingCollections",
      commission_settlement: "operations.finance.report.commissionSettlement",
      three_way_tie_out: "operations.finance.report.threeWayTieOut",
      weekly_scorecard: "operations.finance.report.weeklyScorecard",
    },
  },
  review: {
    dialogTitle: "operations.finance.review.dialogTitle",
    dialogDescription: "operations.finance.review.dialogDescription",
    decisionDescription: "operations.finance.review.decisionDescription",
    terms: {
      entity: "operations.finance.review.term.entity",
      impact: "operations.finance.review.term.impact",
      evidence: "operations.finance.review.term.evidence",
      policy: "operations.finance.review.term.policy",
      downstream: "operations.finance.review.term.downstream",
      authority: "operations.finance.review.term.authority",
    },
    reasonLabel: "operations.finance.review.reasonLabel",
    reasonHelp: "operations.finance.review.reasonHelp",
    decisionReasonHelp: "operations.finance.review.decisionReasonHelp",
    reasonRequired: "operations.finance.review.reasonRequired",
    actorNote: "operations.finance.review.actorNote",
    handoffTitle: "operations.finance.review.handoffTitle",
    handoffBody: "operations.finance.review.handoffBody",
    complete: "operations.finance.review.complete",
    recording: "operations.finance.review.recording",
    recorded: "operations.finance.review.recorded",
    recordDecision: "operations.finance.review.recordDecision",
    decisionRecorded: "operations.finance.review.decisionRecorded",
    errors: {
      reasonRequired: "operations.finance.review.error.reasonRequired",
      recentAuth: "operations.finance.review.error.recentAuth",
      forbidden: "operations.finance.review.error.forbidden",
      notFound: "operations.finance.review.error.notFound",
      invalid: "operations.finance.review.error.invalid",
      unavailable: "operations.finance.review.error.unavailable",
      failed: "operations.finance.review.error.failed",
    },
  },
} as const;
