-- protect_mnda_request (001442): a draft's snapshots and its SignWell binding
-- never change, and completion needs the executed PDF. normalized_company is
-- generated by the same normalizer the duplicate lookups call. The terminal
-- state branch is covered by 1453_esign_reconciled_at.
begin;
select plan(22);
set local search_path = public, extensions;

-- normalized_company
select is(
  (select is_generated from information_schema.columns
    where table_schema = 'public' and table_name = 'commerce_mnda_requests'
      and column_name = 'normalized_company'),
  'ALWAYS', 'the normalized company is generated, never written');
select is(commerce_mnda_normalize_company('Acme, Inc.'), 'acme',
  'punctuation and a trailing entity suffix are ignored');
select is(commerce_mnda_normalize_company('ACME Inc'), commerce_mnda_normalize_company('Acme, Inc.'),
  'case is ignored');
select is(commerce_mnda_normalize_company('Café Société S.A.'), 'cafe societe',
  'accents and dotted suffixes are ignored');
select is(commerce_mnda_normalize_company('Smith & Sons Ltd'), 'smith and sons',
  '"&" reads as "and"');
select is(commerce_mnda_normalize_company('I.B.M. Corp'), 'ibm', 'dotted initials join');
select is(commerce_mnda_normalize_company('Inc'), 'inc', 'a name that is only a suffix keeps it');
select is(commerce_mnda_normalize_company('  ---  '), '', 'a name of punctuation alone is empty');

-- Fixture: an unbound draft without a sender email, and a bound sent request.
insert into commerce_mnda_requests
  (id, input, countersigner, notice_email, owner_id, owner_name, owner_email,
   template_hash, test_mode, state, provider_id)
values
  ('a1442000-0000-4000-8000-000000000001', '{"company":"Pgtap 1442, Inc."}',
   '{"email":"cs@fil-one.test"}', 'notices@fil-one.test',
   'a1442000-0000-4000-8000-0000000000ff', 'Seller', null,
   repeat('a', 64), true, 'draft', null),
  ('a1442000-0000-4000-8000-000000000002', '{"company":"Pgtap 1442 Sent"}',
   '{"email":"cs@fil-one.test"}', 'notices@fil-one.test',
   'a1442000-0000-4000-8000-0000000000ff', 'Seller', 'seller@fil-one.test',
   repeat('a', 64), true, 'sent', 'pgtap-1442-sent');

select is(
  (select normalized_company from commerce_mnda_requests where id = 'a1442000-0000-4000-8000-000000000001'),
  'pgtap 1442', 'a stored request carries its normalized company');

set local role clockwork_service;
select throws_ok(
  $$update commerce_mnda_requests set normalized_company = 'other'
     where id = 'a1442000-0000-4000-8000-000000000001'$$,
  '428C9', null, 'the normalized company cannot be overwritten');

-- Snapshots
select throws_ok(
  $$update commerce_mnda_requests set input = input || '{"company":"Other"}'
     where id = 'a1442000-0000-4000-8000-000000000001'$$,
  'P0001', 'MNDA snapshots and provider binding are immutable', 'the drafted input is fixed');
select throws_ok(
  $$update commerce_mnda_requests set countersigner = '{"email":"other@fil-one.test"}'
     where id = 'a1442000-0000-4000-8000-000000000001'$$,
  'P0001', 'MNDA snapshots and provider binding are immutable', 'the countersigner is fixed');
select throws_ok(
  $$update commerce_mnda_requests set template_hash = repeat('b', 64)
     where id = 'a1442000-0000-4000-8000-000000000001'$$,
  'P0001', 'MNDA snapshots and provider binding are immutable', 'the legal template is fixed');
select throws_ok(
  $$update commerce_mnda_requests set owner_id = 'a1442000-0000-4000-8000-0000000000fe'
     where id = 'a1442000-0000-4000-8000-000000000001'$$,
  'P0001', 'MNDA snapshots and provider binding are immutable', 'the preparer is fixed');
select throws_ok(
  $$update commerce_mnda_requests set test_mode = false
     where id = 'a1442000-0000-4000-8000-000000000001'$$,
  'P0001', 'MNDA snapshots and provider binding are immutable', 'test or live mode is fixed');
select throws_ok(
  $$update commerce_mnda_requests set notice_email = null
     where id = 'a1442000-0000-4000-8000-000000000001'$$,
  'P0001', 'MNDA snapshots and provider binding are immutable', 'the notice email is fixed');
select lives_ok(
  $$update commerce_mnda_requests set owner_email = 'seller@fil-one.test', provider_id = 'pgtap-1442-draft'
     where id = 'a1442000-0000-4000-8000-000000000001'$$,
  'a missing sender email is filled once, and a draft is bound once');
select throws_ok(
  $$update commerce_mnda_requests set owner_email = 'other@fil-one.test'
     where id = 'a1442000-0000-4000-8000-000000000002'$$,
  'P0001', 'MNDA snapshots and provider binding are immutable', 'a recorded sender email is fixed');
select throws_ok(
  $$update commerce_mnda_requests set provider_id = 'pgtap-1442-other'
     where id = 'a1442000-0000-4000-8000-000000000002'$$,
  'P0001', 'MNDA snapshots and provider binding are immutable', 'the SignWell binding is fixed');

-- Completion evidence
insert into commerce_mnda_artifacts (id, request_id, kind, sha256, base64)
values ('a1442000-0000-4000-8000-0000000000a1', 'a1442000-0000-4000-8000-000000000002',
  'original', repeat('c', 64), 'JVBERi0=');
select throws_ok(
  $$update commerce_mnda_requests set state = 'completed'
     where id = 'a1442000-0000-4000-8000-000000000002'$$,
  'P0001', 'MNDA completion requires archived evidence',
  'completion needs the executed PDF, not the original');
insert into commerce_mnda_artifacts (id, request_id, kind, sha256, base64)
values ('a1442000-0000-4000-8000-0000000000a2', 'a1442000-0000-4000-8000-000000000002',
  'executed', repeat('d', 64), 'JVBERi0=');
select lives_ok(
  $$update commerce_mnda_requests set state = 'completed', completed_at = now()
     where id = 'a1442000-0000-4000-8000-000000000002'$$,
  'a request with its executed PDF completes');
select is(
  (select state from commerce_mnda_requests where id = 'a1442000-0000-4000-8000-000000000002'),
  'completed', 'the completed state is stored');

select * from finish();
rollback;
