/**
 * Surface identifiers and workflow kinds shared by the server-backed workflow
 * panel and the routes that mount it.
 */
export type SurfaceKey =
  | "dashboard"
  | "agreements"
  | "agreementExecution"
  | "quotes"
  | "quoteBuilder"
  | "orders"
  | "services"
  | "amendments"
  | "pocs"
  | "billing"
  | "account"
  | "users"
  | "procurement"
  | "offboarding"
  | "marketplace"
  | "support"
  | "partner"
  | "portfolio"
  | "registrations"
  | "registrationDisputes"
  | "partnerQuotes"
  | "partnerBilling"
  | "commissions"
  | "partnerRenewals"
  | "sandboxes"
  | "brand"
  | "partnerMarketplace"
  | "partnerSupport"
  | "internal"
  | "search"
  | "assisted"
  | "queues"
  | "approvals"
  | "priceBooks"
  | "agreementAdmin"
  | "provisioning"
  | "collections"
  | "renewals"
  | "reports"
  | "migrations"
  | "gates";

export type SurfaceWorkflow =
  | "quote"
  | "agreement"
  | "order"
  | "poc"
  | "renewal"
  | "offboarding"
  | "registration"
  | "reports"
  | "payment"
  | "account"
  | "invite"
  | "procurement"
  | "pricebook"
  | "agreementAdmin"
  | "brand"
  | "assisted"
  | "approval"
  | "collections"
  | "admin";
