/** Curated shell icon exports so applications do not depend on transitive packages. */
export {
  ArrowLeftRight,
  BadgeDollarSign,
  Bell,
  BookOpen,
  Building2,
  ChartNoAxesCombined,
  ChevronDown,
  CircleHelp,
  FileDiff,
  FileText,
  FlaskConical,
  Handshake,
  Inbox,
  Layers,
  LayoutDashboard,
  Menu,
  PackageCheck,
  Paintbrush,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Scale,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Stamp,
  TriangleAlert,
  Users,
  WalletCards,
  Webhook,
  X,
} from "lucide-react";
