/** Curated shell icon exports so applications do not depend on transitive packages. */
export {
  BadgeDollarSign,
  Bell,
  Building2,
  ChartNoAxesCombined,
  ChevronDown,
  CircleHelp,
  FileText,
  FlaskConical,
  Handshake,
  Inbox,
  LayoutDashboard,
  Menu,
  PackageCheck,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  ScrollText,
  Search,
  Settings,
  SlidersHorizontal,
  Users,
  WalletCards,
  X,
} from "lucide-react";
