ALTER TABLE "approvals" DROP CONSTRAINT "approvals_two_person_check";--> statement-breakpoint
ALTER TABLE "core_channel_policy_versions" DROP CONSTRAINT "channel_policy_approval_check";--> statement-breakpoint
ALTER TABLE "core_payg_offer_versions" DROP CONSTRAINT "core_payg_offer_approval_check";--> statement-breakpoint
ALTER TABLE "system_capability_requests" DROP CONSTRAINT "system_capability_requests_separation_check";--> statement-breakpoint
ALTER TABLE "approvals" ADD COLUMN "self_approved" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "approvals" ADD COLUMN "self_approval_reason" text;--> statement-breakpoint
ALTER TABLE "exception_cases" ADD COLUMN "self_approved" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "exception_cases" ADD COLUMN "self_approval_reason" text;--> statement-breakpoint
ALTER TABLE "core_channel_policy_versions" ADD COLUMN "self_approved" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "core_channel_policy_versions" ADD COLUMN "self_approval_reason" text;--> statement-breakpoint
ALTER TABLE "core_payg_offer_versions" ADD COLUMN "self_approved" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "core_payg_offer_versions" ADD COLUMN "self_approval_reason" text;--> statement-breakpoint
ALTER TABLE "system_capability_requests" ADD COLUMN "self_approved" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "system_capability_requests" ADD COLUMN "self_approval_reason" text;--> statement-breakpoint
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_self_approval_check" CHECK ((not "approvals"."self_approved" and "approvals"."self_approval_reason" is null) or ("approvals"."self_approved" and "approvals"."approved_by" = "approvals"."requested_by" and "approvals"."status" = 'approved' and length(trim("approvals"."self_approval_reason")) between 8 and 500));--> statement-breakpoint
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_two_person_check" CHECK ("approvals"."approved_by" is null or "approvals"."approved_by" <> "approvals"."requested_by" or "approvals"."self_approved");--> statement-breakpoint
ALTER TABLE "exception_cases" ADD CONSTRAINT "exception_cases_self_approval_check" CHECK ((not "exception_cases"."self_approved" and "exception_cases"."self_approval_reason" is null) or ("exception_cases"."self_approved" and "exception_cases"."status" = 'approved' and "exception_cases"."requester_user_id" is not null and length(trim("exception_cases"."self_approval_reason")) between 8 and 500));--> statement-breakpoint
ALTER TABLE "core_channel_policy_versions" ADD CONSTRAINT "channel_policy_self_approval_check" CHECK ((not "core_channel_policy_versions"."self_approved" and "core_channel_policy_versions"."self_approval_reason" is null) or ("core_channel_policy_versions"."self_approved" and "core_channel_policy_versions"."status" = 'approved' and "core_channel_policy_versions"."approved_by" in ("core_channel_policy_versions"."created_by", "core_channel_policy_versions"."last_edited_by", "core_channel_policy_versions"."proposed_by") and length(trim("core_channel_policy_versions"."self_approval_reason")) between 8 and 500));--> statement-breakpoint
ALTER TABLE "core_channel_policy_versions" ADD CONSTRAINT "channel_policy_approval_check" CHECK ("core_channel_policy_versions"."status"<>'approved' or (
    "core_channel_policy_versions"."approved_by" is not null and "core_channel_policy_versions"."proposed_by" is not null
    and "core_channel_policy_versions"."approval_evidence" is not null and length(trim("core_channel_policy_versions"."approval_evidence"))>=8
    and ("core_channel_policy_versions"."self_approved" or ("core_channel_policy_versions"."approved_by"<>"core_channel_policy_versions"."created_by" and "core_channel_policy_versions"."approved_by"<>"core_channel_policy_versions"."last_edited_by"
      and "core_channel_policy_versions"."approved_by"<>"core_channel_policy_versions"."proposed_by"))
  ));--> statement-breakpoint
ALTER TABLE "core_payg_offer_versions" ADD CONSTRAINT "core_payg_offer_self_approval_check" CHECK ((not "core_payg_offer_versions"."self_approved" and "core_payg_offer_versions"."self_approval_reason" is null) or ("core_payg_offer_versions"."self_approved" and "core_payg_offer_versions"."status" in ('approved','retired') and "core_payg_offer_versions"."approved_by" in ("core_payg_offer_versions"."created_by", "core_payg_offer_versions"."last_edited_by", "core_payg_offer_versions"."proposed_by") and length(trim("core_payg_offer_versions"."self_approval_reason")) between 8 and 500));--> statement-breakpoint
ALTER TABLE "core_payg_offer_versions" ADD CONSTRAINT "core_payg_offer_approval_check" CHECK ("core_payg_offer_versions"."status" not in ('approved','retired') or ("core_payg_offer_versions"."approved_by" is not null and "core_payg_offer_versions"."proposed_by" is not null and "core_payg_offer_versions"."approval_evidence_id" is not null and length(trim("core_payg_offer_versions"."approval_evidence_id")) > 0 and ("core_payg_offer_versions"."self_approved" or ("core_payg_offer_versions"."approved_by" <> "core_payg_offer_versions"."proposed_by" and "core_payg_offer_versions"."approved_by" <> "core_payg_offer_versions"."created_by" and "core_payg_offer_versions"."approved_by" <> "core_payg_offer_versions"."last_edited_by"))));--> statement-breakpoint
ALTER TABLE "system_capability_requests" ADD CONSTRAINT "system_capability_requests_self_approval_check" CHECK ((not "system_capability_requests"."self_approved" and "system_capability_requests"."self_approval_reason" is null) or ("system_capability_requests"."self_approved" and "system_capability_requests"."status" = 'approved' and "system_capability_requests"."decided_by" = "system_capability_requests"."requested_by" and length(trim("system_capability_requests"."self_approval_reason")) between 8 and 500));--> statement-breakpoint
ALTER TABLE "system_capability_requests" ADD CONSTRAINT "system_capability_requests_separation_check" CHECK ("system_capability_requests"."status" <> 'approved' or "system_capability_requests"."decided_by" <> "system_capability_requests"."requested_by" or "system_capability_requests"."self_approved");