export const QUEUE_COPY = {
  loading: "Loading operational queues…",
  eyebrow: "Internal operations",
  title: "Operational queues",
  description:
    "Prioritized policy, provider, and lifecycle work with clear ownership and evidence.",
  freshness: "Projection generated",
  staleTitle: "Data may be stale.",
  staleDescription:
    "At least one record is past its refresh window. Decisions should be verified against the source.",
  staleAction: "Refresh projection",
  savedViewsLabel: "Saved queue views",
  filtersTitle: "Filter queue",
  filtersDescription:
    "Technical identifiers are searchable but kept out of the primary workflow.",
  clearAll: "Clear all",
  searchLabel: "Search work",
  searchPlaceholder: "Entity, work item, or reference",
  resultTableLabel: "Queue results",
  resultCaption: "Operational queue results sorted by SLA, risk, then age",
  detailLabel: "Selected queue item details",
  activeFilters: "Active filters",
  noActiveFilters: "No active filters",
  updating: "Updating queue results…",
  rowsPerPage: "Rows per page",
  previous: "Previous",
  next: "Next",
  table: ["Work item", "Owner", "SLA", "Risk", "Status", "Age"],
  filterLabels: {
    type: "Type",
    owner: "Owner",
    backup: "Backup",
    sla: "SLA",
    risk: "Risk",
    status: "Status",
    age: "Age",
    sort: "Sort",
  },
  states: {
    empty: [
      "No queue work yet",
      "New operational work will appear here when a policy or provider needs attention.",
    ],
    "no-match": [
      "No work matches these filters",
      "Clear one or more filters to broaden the result set.",
    ],
  },
  details: {
    owner: "Owner",
    backup: "Backup",
    risk: "Risk",
    status: "Status",
    created: "Created",
    updated: "Last updated",
    deadline: "Policy deadline",
    reason: "Why this needs a decision",
    policy: "Policy basis:",
    evidence: "Evidence",
    technicalId: "Technical identifier",
    related: "Related records",
    actions: "Permitted actions",
    unavailable: "Queue item unavailable",
    back: "Back to queues",
  },
} as const;

export const SEARCH_COPY = {
  loading: "Loading global search…",
  eyebrow: "Internal operations",
  title: "Global search",
  description:
    "Find available commercial, account, lifecycle, queue, and policy records from one place.",
  label: "Search accounts, records, and documents",
  placeholder: "Try Northstar, an invoice number, or a policy",
  action: "Search",
  keyboardHelp: "move through results · Enter opens the focused title",
  searching: "Searching available records…",
  scopeTitle: "Search across operational records",
  scopeDescription:
    "Results are permission-scoped and grouped by type. Technical identifiers are matched, but human-readable titles stay primary.",
  scope: [
    "Accounts and end clients",
    "Agreements and documents",
    "Quotes, orders, and invoices",
    "Queue work",
  ],
  clear: "Clear search",
  resultsLabel: "Search results",
  grouped: "Grouped by record type · availability reflects your role",
  reference: "Reference",
} as const;
