/** Stable lifecycle audit/outbox topics. Payload schemas evolve via eventVersion. */
export const lifecycleEventTypes = Object.freeze({
  accountRegistered: "account.registered",
  organizationCreated: "organization.created",
  membershipInvited: "membership.invited",
  membershipChanged: "membership.changed",
  accountSelected: "account.selected",
  partnerDomainVerified: "account.partner_domain_verified",
  procurementUpdated: "procurement_profile.updated",
  procurementCompleted: "procurement_profile.completed",
  screeningCompleted: "account.screening_completed",
  agreementTemplateApproved: "agreement.template_approved",
  agreementExecuted: "agreement.executed",
  agreementEnvelopeCreated: "agreement.envelope_created",
  agreementEnvelopeCompleted: "agreement.envelope_completed",
  pocApproved: "poc.approved",
  pocActivated: "poc.activated",
  pocConverted: "poc.converted",
  provisioningRequested: "order.provisioning_requested",
  provisioningConfirmed: "order.provisioning_confirmed",
  provisioningDeadLettered: "order.provisioning_dead_lettered",
  passThroughTermsAccepted: "agreement.pass_through_terms_accepted",
  inboundNoticeRecorded: "inbound_notice.recorded",
  renewalRequested: "renewal.requested",
  renewalDeclined: "renewal.declined",
  terminationRequested: "termination.requested",
  terminationApproved: "termination.approved",
  terminationConfirmed: "termination.teardown_confirmed",
  deletionCertificateIssued: "termination.deletion_certificate_issued",
  novationCompleted: "novation.completed",
  exceptionOpened: "exception_case.opened",
  exceptionDecided: "exception_case.decided",
  migrationStarted: "migration.started",
  migrationReviewRequired: "migration.review_required",
  migrationCompleted: "migration.completed",
  marketplaceEntitlementReceived: "entitlement.marketplace_event_received",
} as const);

export type LifecycleEventType =
  (typeof lifecycleEventTypes)[keyof typeof lifecycleEventTypes];
